### ISSUE TITLE
Logo Design For Checkout Verifier

### ISSUE THREAD

**Issue by zularizal** [ItzNotABug/CheckoutVerifier#1]
Hi @ItzNotABug , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by ItzNotABug** [comment]
Sure..
You can add the Logo in the ReadMe & send a PR.

**Comment by zularizal** [comment]
Hi @ItzNotABug , this is a logo design for your project. This logo is inspired by the checklist icon, network icon and shield icon.
And I have made several color choices for the logo.
What do you think? Which one do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/56635338-6efde400-668f-11e9-96e5-9dfa9dc0f126.png)

**Comment by ItzNotABug** [comment]
Can you make it more simpler?
The network icon looks too techy, I'd prefer something more simpler.. :)
Thanks for your efforts.. :)

**Comment by zularizal** [comment]
I have designed several alternative logos. Which one do you like?

![rect6982](https://user-images.githubusercontent.com/38547278/56721414-084ff780-676f-11e9-8aa7-7475b23246a6.png)

**Comment by ItzNotABug** [comment]
ughh..
its so difficult to choose one.. 😞
I'll go with the One in the Blue gradient, from the one you sent at first!
Icon > Bluish Verify, Network & Shield one :)
Thanks for that & a PR would be great! 😁

**Comment by zularizal** [comment]
Okay, Is this your choice?

![rect7029](https://user-images.githubusercontent.com/38547278/56722878-1ce1bf00-6772-11e9-81d2-88ff677f0ac2.png)

**Comment by ItzNotABug** [comment]
Yes, but the one in Bluish background.. second last.

**Comment by zularizal** [comment]
Okay, I like this one too.
Wait I will make a pr.

![rect7029](https://user-images.githubusercontent.com/38547278/56723148-9c6f8e00-6772-11e9-826e-e3c68bd4f987.png)

**Comment by ItzNotABug** [comment]
yes, this second one.. :)

**Comment by zularizal** [comment]
Hi @ItzNotABug , I sent a pull request.

And also I have uploaded the logo to the drive. Check this link. https://drive.google.com/open?id=1aW2GkJRxiMbjvF5fe1PoPRYTMuqrJNbC
